spring:
  profiles:
    active: default
  config:
    import: 'consul:'
  application:
    name: order-service
  cloud:
    consul:
      host: localhost
      port: 8500
      acl-token: 6e26527b-5e07-5116-4ade-291fdaf683cb
      discovery:
        instance-id: order-service-i1
      config:
        acl-token: 6e26527b-5e07-5116-4ade-291fdaf683cb

server:
  port: 0
