spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  main:
    lazy-initialization: true
  profiles:
    active: default
  config:
    import:
      - 'vault://'
      - 'optional:consul:'
  application:
    name: order-service
  cloud:
    vault:
      uri: http://127.0.0.1:8200
      authentication: TOKEN
      token: root
      kv:
        enabled: true
        backend: secret
        default-context: order-service
        profile-separator: '/'
        secret-backend: secret/data
      generic:
        enabled: true
        application-name: order-service
      consul:
        acl-token: ${acl-token}
    consul:
      host: localhost
      port: 8500

server:
  port: 0

logging:
  level:
    org.springframework.cloud.consul: DEBUG
    org.springframework.cloud.vault: DEBUG
