version: "3.8"
services:
  consul:
    image: hashicorp/consul:1.16.1
    container_name: consul
    ports:
      - "8500:8500"
    command: agent -dev -client=0.0.0.0
    volumes:
      - E:/IdeaProjects/spring_cloud_consule/agent.json:/consul/config/agent.json
    networks:
      - consul-vault-network

  vault:
    image: hashicorp/vault:1.15.3
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    command: server -dev
    networks:
      - consul-vault-network

networks:
  consul-vault-network:
    driver: bridge
