spring:
  profiles:
    active: default
  config:
    import: 'consul:'
  application:
    name: product-service
  cloud:
    consul:
      host: localhost
      port: 8500
      acl-token: f9a95356-bd4d-2503-9e10-a9b87e03e37c
      discovery:
        instance-id: product-service-i1
      config:
        acl-token: f9a95356-bd4d-2503-9e10-a9b87e03e37c
  sql:
    init:
      mode: never # change to 'always' for first running ('never' - for all others)


server:
  port: 0