spring:
  profiles:
    active: default
  config:
    import: 'consul:'
  application:
    name: product-service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instance-id: product-service-i1
        acl-token: 9e7f97fc-8c39-31a2-899f-0adc98515438
      config:
        acl-token: 9e7f97fc-8c39-31a2-899f-0adc98515438
  sql:
    init:
      mode: never # change to 'always' for first running ('never' - for all others)


server:
  port: 0